[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
size = 17.5

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001Ec"
key = "T"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Ep"
key = "Tab"
mods = "Shift|Control"

[[keyboard.bindings]]
chars = "\u001En"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001E1"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E2"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E3"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E4"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E5"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E6"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E7"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E8"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001E0"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Eb"
key = "B"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001El"
key = "L"
mods = "Control"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux new -A -s alacritty"]
program = "/opt/homebrew/bin/fish"

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 3
y = 3
