theme = "custom_nord"

[editor]
line-number = "relative"
mouse = false
shell = ["fish", "-c"]
color-modes = true
idle-timeout = 0
auto-format = false
auto-pairs = false

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
"backspace" = "remove_primary_selection"
"ret" = "keep_primary_selection"
"esc" = "collapse_selection"
"\\" = "command_palette"
"tab" = "rotate_view"
"C-n" = [
  "search_selection",
  "extend_search_next",
]
"space" = { "c" = "toggle_comments", "F" = ":format", "S" = ":pipe sort" }
"[" = { "e" = "goto_prev_diag" }
"]" = { "e" = "goto_next_diag" }
"C" = [
  "collapse_selection",
  "select_mode",
  "goto_line_end",
  "change_selection",
  "normal_mode",
]
"D" = [
  "collapse_selection",
  "select_mode",
  "goto_line_end",
  "delete_selection",
  "normal_mode",
]
"C-j" = "copy_selection_on_next_line"
"C-k" = "copy_selection_on_prev_line"
g = { l = ["select_mode", "goto_line_end", "normal_mode"], h = ["select_mode", "goto_line_start", "normal_mode"], f = "jump_forward", b = "jump_backward" }
"*" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "make_search_word_bounded",
  "search_next",
]
"#" = [
  "move_char_right",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "search_prev",
]
m = { m = ["collapse_selection", "select_mode", "match_brackets", "normal_mode"] }

[keys.select]
"backspace" = "remove_primary_selection"
"ret" = "keep_primary_selection"
"\\" = "command_palette"
"tab" = "rotate_view"
"C-n" = [
  "search_selection",
  "extend_search_next",
]
"space" = { "c" = "toggle_comments", "F" = ":format", "S" = ":pipe sort" }
"[" = { "e" = "goto_prev_diag" }
"]" = { "e" = "goto_next_diag" }
