theme = "nord"

[editor]
line-number = "relative"
mouse = false
shell = ["fish", "-c"]
color-modes = true
idle-timeout = 0
auto-format = false

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true

[keys.normal]
"backspace" = "remove_primary_selection"
"ret" = "keep_primary_selection"
"\\" = "command_palette"
"tab" = "rotate_view"
"C-n" = [
  "select_mode",
  "move_prev_word_start",
  "collapse_selection",
  "move_next_word_end",
  "search_selection",
  "extend_search_next",
]
"space" = { "c" = "toggle_comments", "F" = ":format" }
"[" = { "e" = "goto_prev_diag" }
"]" = { "e" = "goto_next_diag" }
"C" = [
  "collapse_selection",
  "select_mode",
  "goto_line_end",
  "change_selection",
]
"D" = [
  "collapse_selection",
  "select_mode",
  "goto_line_end",
  "delete_selection",
]
"C-j" = "copy_selection_on_next_line"
"C-k" = "copy_selection_on_prev_line"
g = { l = ["select_mode", "goto_line_end", "normal_mode"], h = ["select_mode", "goto_line_start", "normal_mode"] }

[keys.select]
"backspace" = "remove_primary_selection"
"ret" = "keep_primary_selection"
"\\" = "command_palette"
"tab" = "rotate_view"
"C-n" = [
  "select_mode",
  "move_prev_word_start",
  "collapse_selection",
  "move_next_word_end",
  "search_selection",
  "extend_search_next",
]
"space" = { "c" = "toggle_comments", "F" = ":format" }
"[" = { "e" = "goto_prev_diag" }
"]" = { "e" = "goto_next_diag" }
