[[language]]
name = "typescript"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
language-server = { command = "typescript-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "css"
language-server = { command = "vscode-css-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "css"] }

[[language]]
name = "html"
language-server = { command = "vscode-html-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
language-server = { command = "vscode-json-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "json"] }

[[language]]
name = "yaml"
language-server = { command = "yaml-language-server", args = ["--stdio"] }
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "yaml"] }

[[language]]
name = "graphql"
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "graphql"] }

[[language]]
name = "markdown"
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "markdown"] }
