[language-server.typescript]
command = "typescript-language-server"
args = ["--stdio"]
config.hostInfo = "helix"

[language-server.eslint]
args = ["--stdio"]
command = "vscode-eslint-language-server"

[language-server.eslint.config]
nodePath = "node"
onIgnoredFiles = "off"
packageManager = "pnpm"
quiet = false
rulesCustomizations = []
run = "onType"
useESLintClass = false
validate = "on"
codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
codeActionOnSave = { mode = "all" }
experimental = { }
problems = { shortenToSingleLine = false }
workingDirectory = { mode = "auto" }

[language-server.css]
args = ["--stdio"]
command = "vscode-css-language-server"

[language-server.html]
args = ["--stdio"]
command = "vscode-html-language-server"

[language-server.json]
args = ["--stdio"]
command = "vscode-json-language-server"

[language-server.yaml]
args = ["--stdio"]
command = "yaml-language-server"

[language-server.openscad]
args = ["--stdio", "--fmt-style", "Mozilla"]
command = "/Users/gerardomunguia/.cargo/bin/openscad-lsp"

[[language]]
name = "typescript"
language-servers = [
  "typescript",
  { name = "eslint", except-features = [ "format" ] }
]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "javascript"
language-servers = [
  "typescript",
  { name = "eslint" , except-features = [ "format" ] }
]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "jsx"
language-servers = [
  "typescript",
  { name = "eslint" , except-features = [ "format" ] }
]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "tsx"
language-servers = [
  "typescript",
  { name = "eslint" , except-features = [ "format" ] }
]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "typescript"] }

[[language]]
name = "css"
language-servers = ["css"]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "css"] }

[[language]]
name = "html"
language-servers = ["html"]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "html"] }

[[language]]
name = "json"
language-servers = ["json"]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "json"] }

[[language]]
name = "yaml"
language-servers = ["yaml"]
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "yaml"] }

[[language]]
name = "graphql"
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "graphql"] }

[[language]]
name = "markdown"
formatter = { command = "./node_modules/.bin/prettier", args = ["--parser", "markdown"] }

[[language]]
name = "openscad"
language-servers = ["openscad"]
